---

# Configure (simple) the proper firewall ports and services
# For a more robust (but more execution intensive) implementation use the rhel_system_role.firewalld role

- name: "Configure the firewalld services"
  when: firewalld_services is defined and (firewalld_services | length) > 0
  ansible.posix.firewalld:
    service: "{{ firewalld_service.service }}"
    permanent: "{{ firewalld_service.permanent }}"
    immediate: "{{ firewalld_service.immediate }}"
    zone: "{{ firewalld_service.zone }}"
    state: "{{ firewalld_service.state }}"
  loop: "{{ firewalld_services }}"
  loop_control:
    loop_var: firewalld_service

- name: "Configure the firewalld services"
  when: firewalld_ports is defined and (firewalld_ports | length) > 0
  ansible.posix.firewalld:
    port: "{{ firewalld_port.port }}"
    permanent: "{{ firewalld_port.permanent }}"
    immediate: "{{ firewalld_port.immediate }}"
    zone: "{{ firewalld_port.zone }}"
    state: "{{ firewalld_port.state }}"
  loop: "{{ firewalld_ports }}"
  loop_control:
    loop_var: firewalld_port
